### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by philippe44**
Hi - This is a PR to adapt to LMS 8.x backend changes wrt mp4 streams handling. There is now a built-in mp4->aac decoder than can also decide to use native mp4 when possible or do the internal ADTS transformation when necessary. It also means that on-line files are scanned for a small amount till their headers is received. It allows seeking inside online tracks (as long as server supports range-requests) and it also handles mp4 whose header is at the end of the file (using range requests again). There is much less code needed in plugins as a result of these backend changes (including better HTTPS handling)

It also fixes a few things wrt direct streaming as I believe the current version does not handle this option correctly. Now, currently LMS 8.1 has a potential issue with requestString method that I'm discussing here https://github.com/Logitech/slimserver/pull/566 (to be discussed) which forces proxied streaming (but that was already the case anyway). As a result, this is a LMS 8.1 only PR but I really think that 8.0 and below should be made a thing of the past now.

### CODE REVIEW

**Comment by PaulWebster** [comment]
If this change will mean that the plugin will only work with LMS 8.1 and higher then the xml template files will also need their the minimum version changed to 8.1

install.template.xml minVersion
public.template.xml minTarget

**Comment by philippe44** [comment]
yep and I missed that b/c I had the change done on my own install.xml but missed that there are these 2 others

**Comment by danielvijge** [comment]
Thanks for the changes. As the minimum version moves to 8.1, it would be interested to have some statistics of users still using 7.x. That's always been a bit of a problem, that I have no idea how many people are actually using the plugin, or are using a specific version. Are there any known statistics of the install base of 7.x/8.0/8.1+ ?
I run 8.2 nightly, so I don't have a real issue with it. But I might consider making some more changes and publish a version with `maxTarget: 8.0` (freeze of the current version), and your changes going forward with `minTarget: 8.1`

**Comment by philippe44** [comment]
I don't have statistics on <8.1 but I would think that we should push really hard to have everybody migrated. There is really a big gap and to have proper streaming service support, 8.0 and below should be fully deprecated. I personally do not build any workaround in plugins to keep <= 8.0 compatibility.

**Pull request merged**
